### ISSUE TITLE
@XYParameter does not show label

### ISSUE THREAD

**Issue by hamoid** [openrndr/orx#107]
**Describe the bug**
Not sure if bug or feature request, but the @XYParameter in gui does not show the label

**To Reproduce**
Use @XYParameter

**Expected behavior**
Shows the label

**Screenshots**
![](https://aws1.discourse-cdn.com/free1/uploads/openrndr/original/1X/9af299f3fe162da978e1677e6c09e2f24e6e97f0.gif)
(the label is from the previous control)

**Context:**
 - Tested on Linux and Mac
 - Latest OpenRNDR version

Original control by @reinvdwoerd

**Comment by reinvdwoerd** [comment]
Thanks for reminding me of this!

**Comment by reinvdwoerd** [comment]
No half work, I'll fix it tonight! 😅

**Comment by reinvdwoerd** [comment]
Is it ok if I add a demo for it in orx-panel?

**Comment by hamoid** [comment]
Demo for XYParameter in orx-gui sounds good to me :)

**Comment by reinvdwoerd** [comment]
stream of consciousness writing 😂

> Is it ok if I add a demo for it in orx-panel?
> Or is it better to put that in orx-parameters or orx-gui?
> I think I'll put the demo for XYParameter in orx-gui.

**Comment by reinvdwoerd** [comment]
Does this look ok?

<img width="198" alt="Screenshot 2020-05-17 at 20 01 26" src="https://user-images.githubusercontent.com/18028372/82156041-3839d380-9879-11ea-8572-32bae2c7bda8.png">

**Comment by reinvdwoerd** [comment]
No wait, that description is confusing. Let's just call it "Settings"

**Comment by reinvdwoerd** [comment]
https://github.com/openrndr/orx/pull/108

**Comment by hamoid** [comment]
Have you looked how it looks together with other gui elements? It seems like they often have the label under, on the left. But as you did it occupies less space...
![](https://raw.githubusercontent.com/openrndr/orx/media/orx-gui/images/DemoSimple01Kt.png)

Maybe you can take a screenshot with several inputs at once to see how they blend together?

**Comment by reinvdwoerd** [comment]
Good idea

**Comment by reinvdwoerd** [comment]
It does look a little inconsistent

<img width="200" alt="Screenshot 2020-05-17 at 21 55 29" src="https://user-images.githubusercontent.com/18028372/82158595-311ac180-9889-11ea-9927-ee4fb4753da3.png">

**Comment by reinvdwoerd** [comment]
Especially the spacing is off

**Comment by reinvdwoerd** [comment]
I could make a few variations tomorrow...

**Comment by reinvdwoerd** [comment]
This could be an alternative 
<img width="912" alt="Screen Shot 2020-05-19 at 8 57 15 PM" src="https://user-images.githubusercontent.com/18028372/82366956-563b3b80-9a13-11ea-8a61-1f64f6a87050.png">

**Comment by reinvdwoerd** [comment]
Or this

<img width="912" alt="Screen Shot 2020-05-19 at 9 00 47 PM" src="https://user-images.githubusercontent.com/18028372/82367272-d366b080-9a13-11ea-8672-cea2ba8703f4.png">

**Comment by hamoid** [comment]
Last one is my favorite. Not sure how to deal with the overlap... What if the numbers are in the grid but the label below it?
![anotheroption](https://user-images.githubusercontent.com/108264/82445361-f68d7080-9aa4-11ea-8688-5f0e74a38fd9.png)

**Comment by hamoid** [comment]
Hi hi :) Do you still have the code laying around? Would be nice to close this before its 1 year anniversary :-P Cheers!

**Comment by reinvdwoerd** [comment]
Heyyy Abe! I wiped my hard drive a few times this year, but let me check if I still have it in a repository somewhere...

**Comment by hamoid** [comment]
You did that for fun or by accident? :)

**Comment by reinvdwoerd** [comment]
It probably had something to do with a Hackingtosh update, which I was running at the time. But yeah it appears that I deleted my fork, but it shouldn't be so hard to recreate it, I definitely won't let it reach it's one-year anniversary

**Comment by hamoid** [comment]
Closing. The original issue was about a missing label, but the label is already there. Also sent a PR to implement what we discussed above :)
