### ISSUE TITLE
Cannot compare panel UI element colours

### ISSUE THREAD

**Issue by Rolodophone** [openrndr/orx#158]
**Describe the bug**
Cannot compare panel UI element colours - see below

**To Reproduce**
```
println(ColorRGBa.WHITE == ColorRGBa.WHITE) //true as expected
println(Color.RGBa(ColorRGBa.WHITE) == Color.RGBa(ColorRGBa.WHITE)) //false!
```

**Expected behavior**
The second line above to output true

**Comment by hamoid** [comment]
This is one fix:

```
diff --git a/orx-panel/src/main/kotlin/org/openrndr/panel/style/StyleSheet.kt b/orx-panel/src/main/kotlin/org/openrndr/panel/style/StyleSheet.kt
index bae1642..785871c 100644
--- a/orx-panel/src/main/kotlin/org/openrndr/panel/style/StyleSheet.kt
+++ b/orx-panel/src/main/kotlin/org/openrndr/panel/style/StyleSheet.kt
@@ -21,6 +21,10 @@ sealed class Color(inherit: Boolean = false) : PropertyValue(inherit) {
         override fun toString(): String {
             return "RGBa(color=$color)"
         }
+
+        override fun equals(other: Any?): Boolean {
+            return other is RGBa && this.color == other.color
+        }
     }
 
     object Inherit : Color(inherit = true)
```

but someone else should say if it should be fixed :-)

**Comment by Rolodophone** [comment]
Oh, I see. I didn't realise I need to cast it to `Color.RGBa` to access its colour. I was trying to check if the border colour was white using `elem.computedStyle.borderColor == Color.RGBa(ColorRGBa.WHITE)` but I've now realised I can use `(elem.computedStyle.borderColor as Color.RGBa).color == ColorRGBa.WHITE`

**Comment by hamoid** [comment]
I don't fully understand every part of it, but in the three lines I added above, the casting is only needed because of the type `Any?`. And the reason I use `Any?` instead of `RGBa` is that it is required for overriding the `equals` method.

What you could do without changing OPENRNDR is probably this very verbose thing:
`println(Color.RGBa(ColorRGBa.WHITE).color == Color.RGBa(ColorRGBa.WHITE).color)`
Maybe that works?

**Comment by edwinRNDR** [comment]
`StyleSheet` has tools for the background color but not for the border color

```
val StyleSheet.effectiveBackground: ColorRGBa?
    get() = (background as? Color.RGBa)?.color
```
I can add it (or someone can PR it).

In the meanwhile you can create an _extension function_ without changing the `orx-panel` codebase
```
val StyleSheet.effectiveBorderColor: ColorRGBa?
    get() = (borderColor as? Color.RGBa)?.color
```

Which can be used like `element.computedStyle.effectiveBorderColor == ColorRGBa.WHITE`

**Comment by Rolodophone** [comment]
Cool, thanks guys
