### ISSUE TITLE
[orx-noise] Double.gaussian causes StackOverflowError because of unintended recursion

### ISSUE THREAD

**Issue by Yvee1** [openrndr/orx#167]
**Describe the bug**
Calling `Double.gaussian(...)` causes a StackOverflowError.

**To Reproduce**
Call `Double.gaussian(...)`

**Expected behavior**
Identical behavior to calling `gaussian()`

**Additional context**
The issue is that `Double.gaussian` calls `gaussian` internally. The intention was to call the general `gaussian` function but actually `gaussian` refers to `Double.gaussian` itself in that context, causing unintended recursion and hence never-ending function calls.

**Comment by edwinRNDR** [comment]
Addressed in https://github.com/openrndr/orx/commit/8cc54dc35d4c3146647004e42ebc5612b1ba4e37
