### ISSUE TITLE
[orx-midi] Program hangs when closing main window when using MIDI

### ISSUE THREAD

**Issue by megadix** [openrndr/orx#180]
**Describe the bug**

When using MIDI event controllers the program does not close properly when closing the main Window

**To Reproduce**

1. create a simple program
2. initialize a `MidiTransceiver` (see "MIDI" tutorial)
3. register some listeners, e.g. `controlChanged`, `noteOn`, etc.
3. run the program
4. close the main window

**Expected behavior**

When closing the main window the program should exit normally, instead it hangs.

**Context:**
 - OS and version: Windows
 - OpenRNDR version: ~~0.3.15~~ `0.3.46`
 - Java Version: tested with OpenJDK 11 and 14

**Comment by edwinRNDR** [comment]
OPENRNDR 0.3.15 is very old. Can you try this with OPENRNDR 0.3.46?

**Comment by megadix** [comment]
Sorry, my bad, I've put wrong version information!

I'm using the official `openrndr-template` and I took version number from
```kt
group = "org.openrndr.template"
version = "0.3.15"
```
at the top of the `build.gradle.kts` build file. But I was wrong!

The version that's actually used is **`0.3.46`**:

```kt
val openrndrUseSnapshot = false
val openrndrVersion = if (openrndrUseSnapshot) "0.4.0-SNAPSHOT" else "0.3.46"
```

Thank you, I'm sorry for the error.
Dimitri

**Comment by edwinRNDR** [comment]
I believe this was addressed but not documented? Feel free to re-open the issue in case this is still a problem.
