### ISSUE TITLE
orx-gui  features bucket

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/orx#24]
#### Short Term

- [x]  Vector representation - Vector2 is straightforward / Vector3 could be a resizable cube and Vector4 is in need of ideas

- [ ] Variable Histogram - Useful for debugging to see how a variable changes overtime.
- [ ] Palette selector - Be able to preview the colors and change it (orx-palette)
- [x] Collapsible/Hide-able panel bar
- [x] Customisable labels per group
- [x] Randomize button
- [x] Load/Export parameters to JSON

#### Long term:
- [ ] Presets - able to add/change them in runtime/compile (serializable)
	* Exporting parameters with a screenshot and then `git commit` for archiving
- [ ] Bi-directional update - f.ex sliders updated within the runtime have their state reflected in the UI

**Comment by edwinRNDR** [comment]
2738b2f2871ed99e1ff7283b8d6dc6c74c4b29ab adds hiding of the panel using F11. I imagine this would work together with a visual way of hiding the panel.

That same commit also adds a working `@ActionParameter` that can be used to annotate 0 argument functions.

**Comment by edwinRNDR** [comment]
4a819ed5bb85ff6572199c74e6ec8cd7592ec97e adds collapsible parameter compartments and scrolling on the control bar. 

This introduces state (that of the collapsibles) that is reset when `orx-olive` re-evaluates scripts. A best-effort state recovery mechanism should be introduced to provide a good user experience.

**Comment by edwinRNDR** [comment]
84d60b4a518d9a03ff6c34b8fe5965171d8102db adds customized labels during `add()` and generates unique labels in case compartments share the same label.

2af3b89d3622631df45c14a3d56ee6a0c96ac23d uses those compartment labels to track state between script re-evaluations.

**Comment by hamoid** [comment]
Meta: instead of plain bullet points?

- [ ] not done yet
- [x] superdone

```
- [ ] not done yet
- [x] superdone
```

**Comment by edwinRNDR** [comment]
Great tip, thanks @hamoid  :)

**Comment by edwinRNDR** [comment]
5111bd6fb8fd0d582dc43480bf219e7e4c21fe9b takes care of keeping parameter values consistent  between `orx-olive` script re-evaluations. This makes using `orx-olive`'s `Reloadable` no longer necessary (it stilll has its uses for tracking state outside of `orx-gui`'s scope). 

Next step is saving and loading parameter settings to and from json.

**Comment by edwinRNDR** [comment]
8dd4f9236680135c418ec620e8a2780b9cfae144 adds buttons to randomize, load and save parameters. Loading and saving parameters is performed using json files through the Gson library.

**Comment by ricardomatias** [comment]
Closing this in favor of separate issues.
