### ISSUE TITLE
Cannot find FFmpeg artefact on Mac x86_64

### ISSUE THREAD

**Issue by MiguelFranken** [openrndr/orx#278]
I think there is a configuration mistake here. An `x` is missing after `macos`.
Otherwise I'm not able to load the Gradle Project.

https://github.com/openrndr/orx/blob/073fcad54bb07fb04598be8ff53f67adfe4d419f/buildSrc/src/main/kotlin/org/openrndr/extra/convention/FFmpegRule.kt#L18

**Comment by hamoid** [comment]
https://github.com/openrndr/orx/commit/b6d77837c69fadde4362f215619c25a84334a3ce
