### ISSUE TITLE
How to add to my project?

### ISSUE THREAD

**Issue by EdwardDeaver** [openrndr/orx#279]
I'm very new to OPNRNDR and Kotlin. I want to add the noclear module (I'm following this tutorial https://openrndr.discourse.group/t/openrndr-processing-noise-fields-leaving-trails/215) to my code but I'm not sure how to add it to my build. 

How do I add it?

**Comment by hamoid** [comment]
Hi Edward :) Are these instructions enough to make it run? https://guide.openrndr.org/OPENRNDRExtras/#using-openrndr-extras

I'll add a link to the post you linked.

**Comment by EdwardDeaver** [comment]
Thank you! Sorry I didn't see that.
