### ISSUE TITLE
add support for 4D simplex noise in orx-noise

### ISSUE THREAD

**Issue by ylegall** [openrndr/orx#43]
orx-noise is based on the Java implementation of fast noise: https://github.com/Auburns/FastNoise_Java

the current version (0.3.49) only supports 2D and 3D simplex noise. Please also expose or add support for 4D simplex noise, since it is provided in the Java reference implementation.

**Comment by hamoid** [comment]
Hi! I added it here:

https://github.com/hamoid/orx/commit/961fb325d8cf53526abeec0a24ec16a2e095312c

I think I never sent changes to ORX. So I'm not sure if what I did is enough. Does the new class need to mentioned somewhere?

Also, I updated this: https://github.com/hamoid/orx/tree/master/orx-noise but is this part outdated?
```
// -- 2d
val v0 = simplexLinear(seed, x, y)
val v1 = simplexQuintic(seed, x, y)
val v2 = simplexHermite(seed, x, y)

// -- 3d
val v3 = simplexLinear(seed, x, y, z)
val v4 = simplexQuintic(seed, x, y, z)
val v5 = simplexHermite(seed, x, y ,z)

// -- 4d
val v6 = simplexLinear(seed, x, y, z, w)
val v7 = simplexQuintic(seed, x, y, z, w)
val v8 = simplexHermite(seed, x, y, z, w)
```
I don't see those methods in the orx repo...

**Comment by hamoid** [comment]
If https://github.com/openrndr/orx/pull/44 works then this can be closed :)

**Comment by ylegall** [comment]
@hamoid thank you for helping with this. I think you are correct and many parts of the documentation are outdated.

**Comment by edwinRNDR** [comment]
I don't think simplexLinear/Quintic/Hermite ever existed. I have added them recently but I found that simplex noise isn't lattice based in the way perlin and the other noise methods are. So the versions I added are currently broken. I will remove them and update the documentation shortly.
