### ISSUE TITLE
[orx-camera] add short-hand functions for setting drawer state

### ISSUE THREAD

**Issue by edwinRNDR** [openrndr/orx#53]
In use cases like https://openrndr.discourse.group/t/how-to-use-orbitalcamera-and-orbitalcontrols-in-only-some-parts-of-your-program/53/4 it would be handy to have some short-hands for setting both the matrices and the right depth test/write modes. Such that we can call:

```camera.applyTo(drawer)```

or use:
```
camera.isolated(drawer) { 
    // -- draw stuff
}
```

**Comment by hamoid** [comment]
For more context (for myself)

## Every drawn on the screen is rotated by the camera

        val camera = OrbitalCamera(Vector3.UNIT_Z * 1000.0, Vector3.ZERO, 90.0, 0.1, 2000.0)
        val controls = OrbitalControls(camera, keySpeed = 10.0)
        extend(camera)
        extend(controls)

## Some things are rotated by the camera

```
val camera = OrbitalCamera(Vector3.UNIT_Z * 1000.0, Vector3.ZERO, 90.0, 0.1, 2000.0)
val controls = OrbitalControls(camera, keySpeed = 10.0)
extend(controls)
extend {
    camera.update(deltaTime)
    // -- draw in ortho here
    
    drawer.isolated { 
        drawer.perspective(camera.fov, width.toDouble() / height, camera.near, camera.far)
        drawer.view = camera.viewMatrix()
        drawer.drawStyle.depthWrite = true
        drawer.drawStyle.depthTestPass = DepthTestPass.LESS_OR_EQUAL
        // -- draw in perspective here
    }
   // -- draw in ortho here
}
```

Use the previous code for the `applyTo` implementation.

`camera.isolated` will be similar to `drawer.isolated`.

See https://openrndr.slack.com/archives/CEASC1PB7/p1584368670473900

**Comment by hamoid** [comment]
https://github.com/openrndr/orx/pull/57
