### ISSUE TITLE
[README] Missing entries

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/orx#56]
It's missing a few of the newer extensions.. Also could use a facelift, maybe adding the openrndr logo and a few example images. Thoughts?

**Comment by hamoid** [comment]
Should I make a script to generate the content for that file?

It could find all folders starting with orx, grab the name, then read the `readme.md` in that folder and grab the third row until the first period.

The script would just output that content, and it would be the users task to copy that content and paste it into the readme after verifying it worked.

Or I make it really run and forget, producing the whole readme.md. If it doesn't look right then it would be the users job to fix the readme.md in the subfolder... What do you think?

**Comment by edwinRNDR** [comment]
@hamoid generating that `readme.md` could be part of the gradle build. Wondering if it is possible to mix kotlin script and groovy.

**Comment by hamoid** [comment]
I see. I made a first prototype:

```
import java.io.File

val path = "."

val folders = File(path).listFiles { _, name ->
  name.startsWith("orx-") && 
  !name.contains("-natives-") && 
  !name.contains("-demo")
}.sorted()

folders.forEach { 
  val readme = "${it.name}/README.md"
        val file = File(readme)
  val desc = if (file.exists()) file.readLines()[2] else "Description coming soon"

  println("- [`${it.name}`](${readme}), ${desc}") 
}
```

I run it typing `kotlin README.kts`

Which shows there's things to fix in the readmes. I think I would leave the third line in each orx readme for a brief description to be shown in the front page.

A thumbnail for each ORX would be also cool.

I know nothing about groovy :)

**Comment by hamoid** [comment]
Did you mean gradle or groovy @edwinRNDR ? Does this help? https://stackoverflow.com/questions/39576170/proper-way-to-run-kotlin-application-from-gradle-task

**Comment by edwinRNDR** [comment]
@hamoid I think that helps. I have recently updated the README by hand. But would like to automate this in the future

**Comment by hamoid** [comment]
I guess this can be closed, as I added task to update the readme:
https://github.com/openrndr/orx/blob/master/build.gradle#L109

**Comment by hamoid** [comment]
We just have to remember to use it :) or automate it...

**Comment by ricardomatias** [comment]
Perhaps adding a [PR template](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) would help tackling this

**Comment by edwinRNDR** [comment]
I think we never set up the README.md generator to be executed on commit?

**Comment by hamoid** [comment]
No we didn't. How would you do that?

**Comment by edwinRNDR** [comment]
That should be adding the right task to `.github/workflows/generate-screenshots.yaml` when it invokes gradle plus making sure that the generated file is committed (I suspect the current regexp doesn't cover it)

**Comment by hamoid** [comment]
Did we reduce the java version required in build.gradle? Or was it always 1.8?

`./gradlew buildMainReadme` is failing because it uses `String.strip()` and `String.repeat()`.

Should I write replacements for those functions? Or require Java 11?

**Comment by edwinRNDR** [comment]
That has always been Java 8, reason is to maximize compatibility, but maybe that is not so much of an issue anymore now that IntelliJ IDEA ships with Java 11.

**Comment by hamoid** [comment]
I don't know why it used to work for me then.

What do you think then? Rewrite? Or Java 11?

**Comment by hamoid** [comment]
I figured out I can use `.trim()` instead of `.strip()` (as long as we don't use unicode characters).

How does this look like?

```
      - name: Collect screenshots
        run: xvfb-run ./gradlew collectScreenshots
      - name: Build main readme
        run: |
          xvfb-run ./gradlew buildMainReadme
          git add README.md 
          git commit -m "add auto-generated README" 
          git push 
      - name: Prepare media branch
        run: |
          git config --global user.email "actions@openrndr.org"
          git config --global user.name "OPENRNDR Actions"
          git reset HEAD -- .
          (git add [a-z-]*/README.md && git commit -m "add demos to README.md" && git
          git checkout --orphan media
          git reset HEAD -- .
          git add [a-z-]*/images/*.png
          git commit -m "add auto-generated media"
          git push -f origin media 
```
I added the `Build main readme` section. I'm not sure about those 3 git commands, as I've never created an gh action before.

**Comment by hamoid** [comment]
The action is now updated and the readme should update automatically on push.

The script will skip the first line (headline) of the orx readme, then read all the following lines containing text until an empty line. Ideally that description will not mention openrndr, as it would look very repetitive in the main readme to read "x for openrndr, y for openrndr, z ..." :-)
