### ISSUE TITLE
orx-noise: implement Vector2, 3 and 4 versions of functions taking 2, 3 or 4 values

### ISSUE THREAD

**Issue by hamoid** [openrndr/orx#80]
**Is your feature request related to a problem? Please describe.**

I often want to get a random value based on a position. The position might be a Vector3.
Then I need to call `Random.value(position.x, position.y, position.z)` instead of `Random.value(position)`

**Describe the solution you'd like**

Should we implement a few extra methods in Random that take VectorN as input?

**Describe alternatives you've considered**

Continue using the current approach?

**Additional context**

.

**Comment by hamoid** [comment]
Also

    Random.simplex(center.x * 0.01, center.y * 0.01)

would become 

    Random.simplex(center * 0.01)

**Comment by edwinRNDR** [comment]
Good points. Preferably those would be added to the fundamental functions too (`perlin`, `simplex`, `cubic`, etc.. )

**Comment by hamoid** [comment]
I will do that

**Comment by hamoid** [comment]
Merged at https://github.com/openrndr/orx/pull/81
