### ISSUE TITLE
[orx-olive] Scriptless mode fails if file is in a package

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/orx#87]
If a Program file called Sketch.kt is in a package called `sketches`, the `rootClassName` resolves to `sketches.Sketch`. Which `File` doesn't resolve correctly and can't find any candidate program.

**Comment by edwinRNDR** [comment]
Should be improved since bade284622bca7b925d0decd9589e3bf821ab505

**Comment by edwinRNDR** [comment]
Recently improved this in https://github.com/openrndr/orx/commit/75fcb6d5affad11a0cfb064854703cda37b809cb. I think there are still some cases in which things may go wrong. Closing issue for now.
